language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "kitbunrong-github"
    token:
      secure: "hRriL78HbC/pHM8GpCytgocb1TQbD3Hjn5eAOFR1WxAKHoFBXQX0X4SapmcAflHPLo+qs3UhDB9tlj1oQnodPeloJzQ9f9PUQ0MFeYO7LnFC2uSeTNb3Y6OSyhrV7VNRXQ711I8gJ0YVfvNK8ya7XoeBx+gs58wgwJ7SbjBJFEQhHaY5SSaj2K3wNhMjKCBuV1dXAbN4G7Cf4D66Z89d70yg4hS02P1GADhIyXYb6GVbajVbSfTRou+b8pMQotkTb0cAq4hRN4rJJhgEp8Kp1M8CciLaybM6qY2F+d+cAyY782ua8Ixm57LhYywpptCHWoVWCYVMOxoxo5cKXrM3P5vltOB9lrL10TiZBW+VwZF6ROTdJ+1G8UC/eVcLdS7autT7Uci0em+/4brBrlWXL+hzAXt2sOZGrbb6A7qFM4baEVIY75sjpL+hkxiY/dXhbRjBidCdau7T+U7u6sw/uEivJKNOp7ujKnO18TQbHrPFnFx/RwMGsgCul/Mz1+M+xAUUR2jiqMyv2H8/TuRvUUTU9gbc7iJ+zhTCutMYEd42xb6A4FG5n2SySNrkrJai3168cgQuhOX/PJqVoreEha3jeW4/gZJ5hxhT3Op3rVO+yZpe80B8LoN6bPiRGUDSmvwWtubF094QlWPC5MZAm+wdfWorPrLN5pKCJmZvFaA="
jdk:
  - oraclejdk8 -X
  
script:
  - jdk_switcher use oraclejdk8
  - sonar-scanner -X
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
notification:
  email: false